/* Generated by Yosys 0.44 (git sha1 80ba43d26, clang++ 15.0.0 -fPIC -O3) */

module clk_divider_8(clk, sck, en);
  wire [2:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire [2:0] _015_;
  wire [31:0] _016_;
  wire [31:0] _017_;
  wire [31:0] _018_;
  wire [2:0] _019_;
  wire [31:0] _020_;
  wire [31:0] _021_;
  wire [31:0] _022_;
  wire [31:0] _023_;
  wire _024_;
  wire [31:0] _025_;
  wire _026_;
  wire [31:0] _027_;
  wire [31:0] _028_;
  wire [31:0] _029_;
  wire _030_;
  wire [31:0] _031_;
  wire [31:0] _032_;
  wire [31:0] _033_;
  wire [1023:0] _034_;
  wire [31:0] _035_;
  wire [31:0] _036_;
  wire [31:0] _037_;
  wire [31:0] _038_;
  wire [31:0] _039_;
  wire [31:0] _040_;
  wire [31:0] _041_;
  wire [31:0] _042_;
  wire [31:0] _043_;
  wire [31:0] _044_;
  wire [32:0] _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  input clk;
  wire clk;
  wire [2:0] divider;
  input en;
  wire en;
  output sck;
  wire sck;
  INV _156_ (
    .I(_003_),
    .ZN(_010_)
  );
  INV _157_ (
    .I(_002_),
    .ZN(_011_)
  );
  INV _158_ (
    .I(_001_),
    .ZN(_012_)
  );
  NAND2 _159_ (
    .A1(_002_),
    .A2(_001_),
    .ZN(_004_)
  );
  INV _160_ (
    .I(_004_),
    .ZN(_005_)
  );
  NAND2 _161_ (
    .A1(_003_),
    .A2(_004_),
    .ZN(_006_)
  );
  NAND2 _162_ (
    .A1(_010_),
    .A2(_005_),
    .ZN(_007_)
  );
  NAND2 _163_ (
    .A1(_006_),
    .A2(_007_),
    .ZN(_014_)
  );
  NAND2 _164_ (
    .A1(_011_),
    .A2(_012_),
    .ZN(_008_)
  );
  NAND2 _165_ (
    .A1(_004_),
    .A2(_008_),
    .ZN(_009_)
  );
  INV _166_ (
    .I(_009_),
    .ZN(_013_)
  );
  DFFRNQ _167_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(divider[0]),
    .RN(en)
  );
  DFFRNQ _168_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(divider[1]),
    .RN(en)
  );
  DFFRNQ _169_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(divider[2]),
    .RN(en)
  );
  assign _018_[2:0] = _000_;
  assign sck = divider[2];
  assign _027_ = _040_;
  assign _028_ = _039_;
  assign _029_ = { _018_[31:3], _000_ };
  assign _022_ = 32'd1;
  assign _019_ = divider;
  assign _020_ = _021_;
  assign _023_ = _043_;
  assign _039_ = _044_;
  assign { _018_[31:3], _000_ } = _045_[31:0];
  assign _031_ = _040_;
  assign _032_ = _041_;
  assign _033_ = _039_;
  assign _034_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _035_ = _040_;
  assign _038_[0] = _039_[0];
  assign _037_ = 32'd32;
  assign _036_ = 32'd0;
  assign _025_ = 32'd1;
  assign _021_ = { 29'h00000000, divider };
  assign _003_ = divider[2];
  assign _002_ = divider[1];
  assign _001_ = divider[0];
  assign _045_[2] = _014_;
  assign _045_[1] = _013_;
  assign _045_[0] = _012_;
endmodule
